### ISSUE TITLE
Cambiar mail en "próximamente"

### ISSUE THREAD

**Issue by dnchia** [VendingOnTime/vendingontime.github.io#16]

**Comment by agonper** [comment]
Al no tener mailer de momento, he pensado que será mejor quitarlo. En el momento que tengamos un mailer, se añade de nuevo #29

**Comment by agonper** [comment]
Mismo que #11 @dnchia ?

**Comment by msalegre** [comment]
Issue cerrado ya que se ha eliminado el formulario.
