### ISSUE TITLE
Tamaño imágenes miembros equipo

### ISSUE THREAD

**Issue by msalegre** [VendingOnTime/vendingontime.github.io#7]
El tamaño de las imágenes de los miembros del equipo no es correcto. Investigar qué tamaño hay que usar para que sean responsive.

**Comment by msalegre** [comment]
@albertogonper ha solucionado los errores de posicionamiento. De todas formas, sigue habiendo problemas cuando la pantalla es tamaño XS (las imágenes no tienen separación vertical entre ellas y no están centradas).

**Comment by agonper** [comment]
Me asigno para mirarlo

**Comment by agonper** [comment]
Mirar #40
